version: '3.4'

services:
  ecomm.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6002:80"
      #- "8002:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ecomm.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #  - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6003:80"
     # - "8003:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ecomm.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6001:80"
      #- "8001:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ecomm.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - Services__Products=http://ecomm.api.products
      - Services__Customers=http://ecomm.api.customers
      - Services__Orders=http://ecomm.api.orders
    ports:
      - "6004:80"
      #- "8004:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
